---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: appleapprc
spec: 
  replicas: 15
  selector: 
    app: appleapp
  template:
    metadata:
      name: appleapppod
      labels:
        app: appleapp
    spec:
      containers:
        - name: appleappcontainer
          image: javeedit/apple_app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appleappsvc
spec:
  type: NodePort
  selector: 
    app: appleapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30009
...