---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactfrontenddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contactfrontend
  template:
    metadata: 
      name: contactfrontendpod
      labels:
        app: contactfrontend
    spec:
      containers: 
        - name: contactfrontendcontainer
          image: javeedit/contactui
          ports:  
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contactfrontendsvc
spec:
  type: LoadBalancer
  selector: 
    labels: contactfrontend
  ports:
    - port: 80
      targetPort: 80
...