---
apiVersion: v1
kind: ReplicationController
metadata:
  name: luminousapprc
spec:
  replicas: 20
  selector:
    app: luminousapp
  template:
    metadata:
      name: luminousapppod 
      labels:
        app: luminousapp
    spec:
      containers:
        - name: luminousappcontainer
          image: javeedit/luminous_app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: luminousapp
spec:
  type: NodePort
  selector:
    app: luminousapp 
  ports:
    - port: 80
      targetPort: 8080
...

    
