---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: pnbapprc
spec: 
  replicas: 10
  selector:
    app: pnbapp
  template:
    metadata:
      name: pnbapppod
      labels:
        app: pnbapp
    spec:
      containers:
        - name: pnbappcontainer
          image: javeedit/pnb_bank_app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: pnbappsvc
spec: 
  type: NodePort
  selector:
    app: pnbapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30006
...