---
apiVersion: v1
kind: ReplicationController
metadata:
  name: javaapprc
spec:
  replicas: 3
  selector:
    app: javaapp
  template:
    metadata: 
      name: javaapppod  
      labels: 
        app: javaapp
    spec:
      containers:
      - name: javaappcontainer
        image: ashokit/javawebapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: javaappsvc
spec: 
  type: NodePort
  selector:
    app: javaapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005
...